Bugfix/all UI components
peaksoft-school/peaksoft-lms-b-web pull request #18
Opened 2022-04-29 17:25 UTC by shastik007

fixed all ui components

2022-04-29 17:26 UTC, shastik007 commented
please check faster

2022-04-30 06:18 UTC, zhumabek requested changes

2022-04-30 06:18 UTC, zhumabek commented on src/components/UI/BasicModal.jsx
>                       Cancel
Текст всегда эле cancel боло береби?

2022-04-30 06:18 UTC, zhumabek commented on src/components/UI/BasicModal.jsx
>                       Add
Текст всегда элеби Add болобу?

2022-04-30 06:18 UTC, zhumabek commented on src/components/UI/Cards.jsx
> +export const Cards = ({ image, title, duration, description }) => {
а где meatBalls?

2022-04-30 06:18 UTC, zhumabek commented on src/components/UI/Cards.jsx
>        <Card>
Card га onClick болбойт беле?

2022-04-30 09:17 UTC, zhumabek requested changes
А эмне мен удалить бассам meatball’s дон жон эле жабылып калабы удаление кылбайбызбы? Тоже скмое и остальные

2022-04-30 13:17 UTC, zhumabek requested changes

2022-04-30 13:17 UTC, zhumabek commented on src/components/UI/Cards.jsx
> +   }
Через пропс келиш керек да апей
OnDelete onEdit и т.д. Потому что запростор компоненттин сыртында болуш керек да

2022-04-30 14:42 UTC, zhumabek requested changes

2022-04-30 14:42 UTC, zhumabek commented on src/components/UI/Cards.jsx
> +   deleteFunciton,
deleteFunciton? 

туура жаз

анан айттым эле го onDelete onEdit деп кадимки event тердей кылып ат коебуз деп

2022-04-30 14:55 UTC, merged