create-table-component
peaksoft-school/peaksoft-lms-b-web pull request #19
Opened 2022-05-01 09:51 UTC by erkulow

2022-05-01 09:56 UTC, shastik007 commented on src/components/UI/Table.jsx
> +            <TrashBinIcon onClick={onDeleteHdandler} />
замени икрнки на iconsbutton

2022-05-01 09:57 UTC, erkulow commented on src/components/UI/Table.jsx
> +            <TrashBinIcon onClick={onDeleteHdandler} />
Хорошо😂

2022-05-01 13:30 UTC, zhumabek requested changes

2022-05-01 13:30 UTC, zhumabek commented on src/components/UI/Table.jsx
> +`
А что эту таблицу мы используем только для юзеров? Почему userData?

2022-05-01 13:30 UTC, zhumabek commented on src/components/UI/Table.jsx
> +      Действия: (
Действия тоже должны приходить через пропс

Допустим что если мне дейтсвия не нужны? А сейчас полюбому действия деген болот экен сенде

2022-05-01 19:25 UTC, zhumabek requested changes

2022-05-01 19:25 UTC, zhumabek commented on src/App.jsx
> +         'Имя Фамилия': 'Anna Karimova ',
Разве из бекенда данные в таком формате будут приходить? 
ни разу не видел чтобы имя приходил именно таким готовым ключом 'Имя Фамилия'
нет из бекенда данные будут приходить не так как вы хотели бы так что этот формат не подходит

2022-05-04 19:16 UTC, zhumabek requested changes

2022-05-04 19:16 UTC, zhumabek commented on src/components/UI/Table.jsx
> +               return column.action(row)
column.action td тэгдин ичинде болуш керек го дейм

2022-05-04 19:16 UTC, zhumabek commented on src/App.jsx
> +   // ADMIN_PANEL
Ведь нужно удалить тестовый код

2022-05-05 04:03 UTC, zhumabek requested changes

2022-05-05 04:03 UTC, zhumabek commented on src/App.jsx
>     const DATA_COLLUMN = [
я же сказал что нужно удалить все что не нужное в App.js
сколько раз повторять

2022-05-05 04:56 UTC, merged